### ISSUE TITLE
Trouble with Heroku

### ISSUE THREAD

**Issue by Raemon** [brack3t/Djrill#91]
Djrill worked seamlessly on my local machine. But when I pushed to the heroku master, I got the following error:

2015-05-13T21:16:44.369531+00:00 app[web.1]: Traceback (most recent call last):
2015-05-13T21:16:44.369532+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2015-05-13T21:16:44.369533+00:00 app[web.1]:     worker.init_process()
2015-05-13T21:16:44.369535+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2015-05-13T21:16:44.369536+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-05-13T21:16:44.369537+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-05-13T21:16:44.369538+00:00 app[web.1]:     self.callable = self.load()
2015-05-13T21:16:44.369540+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-05-13T21:16:44.369543+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-05-13T21:16:44.369559+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2015-05-13T21:16:44.369554+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
2015-05-13T21:16:44.369557+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
2015-05-13T21:16:44.410079+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-05-13T21:16:44.410081+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-05-13T21:16:44.410082+00:00 app[web.1]:     self.callable = self.load()
2015-05-13T21:16:44.410084+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-05-13T21:16:44.410085+00:00 app[web.1]:     return self.load_wsgiapp()
2015-05-13T21:16:44.410086+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-05-13T21:16:44.410088+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-05-13T21:16:44.410089+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2015-05-13T21:16:44.410091+00:00 app[web.1]:     __import__(module)
2015-05-13T21:16:44.410092+00:00 app[web.1]:   File "/app/agora/wsgi.py", line 17, in <module>
2015-05-13T21:16:44.369558+00:00 app[web.1]:     module = import_module(entry)
2015-05-13T21:16:44.410093+00:00 app[web.1]:     application = Cling(get_wsgi_application())
2015-05-13T21:16:44.410094+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
2015-05-13T21:16:44.410096+00:00 app[web.1]:     django.setup()
2015-05-13T21:16:44.410099+00:00 app[web.1]:     apps.populate(settings.INSTALLED_APPS)
2015-05-13T21:16:44.410100+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
2015-05-13T21:16:44.410067+00:00 app[web.1]: [2015-05-13 21:16:44 +0000] [10] [ERROR] Exception in worker process:
2015-05-13T21:16:44.410078+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2015-05-13T21:16:44.369560+00:00 app[web.1]:     __import__(name)
2015-05-13T21:16:44.369561+00:00 app[web.1]: ImportError: No module named djrill

I've run "pip install djrill" (while in a virtualenv). I've added "djrill" as an Installed App and added these lines to my settings:

MANDRILL_API_KEY = "(( my Mandrill key))"
EMAIL_BACKEND = "djrill.mail.backends.djrill.DjrillBackend"

Is there a step I'm missing? It seems heroku can't find the module.

**Comment by medmunds** [comment]
It sounds like Djrill isn't getting installed into your Heroku environment.

When you say you've run "pip install djrill", was that on your local development machine, or somehow in Heroku? If it was only on your local machine, you need to find a way to tell Heroku you need that package installed when it deploys your project.

I'm not too familiar with Heroku, but in many python deployments, that's a file called `requirements.txt` that has your list of package dependencies (and which you can generate pretty easily with `pip freeze` locally).

**Comment by medmunds** [comment]
Yep, looks like Heroku uses requirements.txt just like the rest of us: https://devcenter.heroku.com/articles/python-pip

So you'll need to add a djrill line to your requirements.txt. See the Heroku article for more info.

**Comment by Raemon** [comment]
Thanks!
